POST http://localhost:3000/api/links
Content-Type: application/json

{
    "code": "andersonbosa",
    "url": "https://andersonbosa.vercel.app"
}

###

GET http://localhost:3000/api/links

###

GET http://localhost:3000/code/andersonbosa

###

GET http://localhost:3000/api/metrics